name: Example Workflow
on:
  push:
    branches:
      - '*'

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Example Step
        run: echo "This is an example action triggered on branch creation"

